---
title: "Main"
author: "Freddie J. Heather"
date: "`r Sys.Date()`"
output: html_document
---

# Set-up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(colorspace)

source("functions.R")
```

# Simulation input

```{r}

max_length <- 60
m_gridsize <- 0.01
k_gridsize <- 0.01
l50_gridsize <- 1
l95_gridsize <- 0.1

sim_input <- 
  bind_rows(
    # Selectivity (3 x MK ratios)
    expand_grid(
      tibble(m = c(0.2, 0.3, 0.4),
             k = c(0.4, 0.2, 0.2)),
      cv_a = 0.1
    ), 
    # MK (3 x CV-at-age)
    expand_grid(
      cv_a = c(0.05, 0.1, 0.2),
      k = seq(0.1, 1.5,  by = 0.05), 
      m = seq(0.1, 1.5, by = 0.05)
    )
  )

# sim_input <- 
#    expand_grid(
#       # tibble(m = c(0.2, 0.3, 0.4), 
#       #        k = c(0.4, 0.2, 0.2)), 
#        tibble(m = c(0.05, 0.1, 0.2, 0.4), 
#              k = c(0.1, 0.2, 0.4, 0.8)), 
#       cv_a = 0.1
#     )

```

# Comparing the three distributions

```{r}

# L50 = midpoint
# L95 = 95th percentile 
logistic_selection <- function(l, l50, l95) {
  1 / (1 + exp(-(log(19)*((l - l50)/(l95-l50)))))
}
# 
# tibble(x = seq(1, 50, by = 0.1)) %>% 
#   mutate(ls = logistic_selection(x, 25, 50)) %>% 
#   ggplot(aes(x, ls)) +
#   geom_line()
# 
# tibble(length = seq(1, 50, by = 0.1)) %>% 
#   mutate(abun = dnorm(length, mean = 30, sd = 3)) %>% 
#   mutate(selected_abun = abun*logistic_selection(abun, l50=25, l95=50)) %>% 
#   ggplot(aes(x, y)) +
#   geom_line() +
#   geom_line(aes(y = y2), col = "red")

```

# Simulations

```{r}

# functions to extract from sizefreq_sim
get_lengths <- function(x) x[[1]][[1]]$Length.classes
get_abunds <- function(x) x[[1]][[1]]$Unfished.Number

sim_ar <- 
  sim_input %>% 
  mutate(sim1 = pmap(.l = list(M = m, k = k, CV.Linf = cv_a, 
                               Linf = max_length), 
                     .f = sizefreq_sim)) %>% 
  mutate(l = map(.x = sim1, 
                 .f = get_lengths), 
         n = map(.x = sim1, 
                 .f = get_abunds)) %>% 
  select(m, k, l, n, cv_a) %>% 
  unnest(cols = c(l, n))

sim_cr <- 
  sim_input %>% 
  mutate(pred = pmap(.l = list(m = m,
                               k = k, 
                               cv = cv_a, 
                               linf = max_length), 
                     .f = sizeComp)) %>% 
  unnest(cols = pred) %>% 
  select(m, k, l = L, n = Nl, cv_a)

```

# RLS binning

```{r}

rls_bin_breaks <- 
  c(2.5, 5.0, 7.5,  10.0, 12.5, 15.0, 20.0, 25.0, 30.0, 35.0, 40.0, 
    50.0, 62.5, 75.0, 87.5, 100.0, 112.5, 125.0, 137.5, 150.0, 
    162.5, 175.0, 187.5, 200.0, 250.0, 300.0, 350.0, 400.0)

rls_bin_table <-
  tibble(size_class = c(0, rls_bin_breaks, 500)) %>% 
  mutate(
    size_min = (size_class + lag(size_class))/2,
    size_max = lead(size_min)
  ) %>% 
  filter(size_class %in% c(rls_bin_breaks, 500))

sim_ar_binned <- 
  sim_ar %>% 
  mutate(l = rls_bin_table$size_class[.bincode(l, rls_bin_table$size_min)]) %>%
  drop_na() %>% 
  summarise(n = sum(n), 
            .by = c(m, k, cv_a, l)) 

sim_cr_binned <- 
  sim_cr %>% 
  mutate(l = rls_bin_table$size_class[.bincode(l, rls_bin_table$size_min)]) %>%
  drop_na() %>% 
  summarise(n = sum(n), 
            .by = c(m, k, cv_a, l)) 

```


# Combine the simulation results

```{r}

sim_summary <- 
  sim_ar %>% 
  mutate(sim = "ar") %>% 
  bind_rows(sim_cr %>% 
              mutate(sim = "cr")) %>% 
  summarise(mean = sum(l*n)/sum(n), 
            sd = sqrt(sum(n * (l - mean)^2) / sum(n)), 
            .by = c(m, k, cv_a, sim)) %>% 
  mutate(cv = sd/mean)

sim_binned_summary <- 
  sim_ar_binned %>% 
  mutate(sim = "ar") %>% 
  bind_rows(sim_cr_binned %>% 
              mutate(sim = "cr")) %>% 
  summarise(mean = sum(l*n)/sum(n), 
            sd = sqrt(sum(n * (l - mean)^2) / sum(n)), 
            .by = c(m, k, cv_a, sim)) %>% 
  mutate(cv = sd/mean)


```

# Selectivity

```{r}

sim_select <- 
  sim_ar %>% 
  mutate(sim = "ar") %>% 
  bind_rows(sim_cr %>% 
              mutate(sim = "cr")) %>%
  filter(m %in% c(0.2, 0.3, 0.4),
          k %in% c(0.4, 0.2, 0.2),
         cv_a == 0.1) %>%
   # filter(m %in% c(0.05, 0.1, 0.2, 0.4), 
   #           k %in% c(0.1, 0.2, 0.4, 0.8), 
   #       cv_a == 0.1) %>% 
  expand_grid(l50 = seq(1, max_length, by = 1),
      l95_const = seq(1.05, 2, by = 0.05)) %>% 
  mutate(l95 = l50*l95_const) %>% 
  mutate(n_s = n*logistic_selection(l, l50=l50, l95=l95))

sim_select_binned <-
  sim_select %>% 
  mutate(rls = rls_bin_table$size_class[.bincode(l, rls_bin_table$size_min)]) %>% 
  drop_na() %>%
  summarise(n_s = sum(n_s), 
            .by = c(rls, cv_a, sim, l50, l95_const, l95, m, k))


sim_select_summary <- 
  sim_select  %>% 
  summarise(mean = sum(l*n_s)/sum(n_s), 
            sd = sqrt(sum(n_s * (l - mean)^2) / sum(n_s)), 
            .by = c(m, k, l50, l95, cv_a, sim)) %>% 
  mutate(cv = sd/mean)

sim_select_summary_binned <- 
  sim_select_binned  %>% 
  summarise(mean = sum(rls*n_s)/sum(n_s), 
            sd = sqrt(sum(n_s * (rls - mean)^2) / sum(n_s)), 
            .by = c(m, k, l50, l95, cv_a, sim)) %>% 
  mutate(cv = sd/mean)

```

# Plotting 

## Figure 4

```{r}

sim1 <- sizefreq_sim(Linf = max_length,
             M = 0.3, 
             k = 0.2, 
             CV.Linf = 0.1)

sim2 <- sizeComp(linf = max_length,
             m = 0.3, 
             k = 0.2, 
             cv = 0.1) %>% 
  select(l = L, n = Nl)

tibble(l = get_lengths(sim1), 
       n = get_abunds(sim1)) %>% 
  mutate(sim = "ar") %>% 
  


tibble(l = seq(1, 60, by = 0.1)) %>% 
  mutate(logis = logistic_selection(l, 25, 50)) %>% 
  ggplot(aes(x, ls)) +
  geom_line()

tibble(length = seq(1, 50, by = 0.1)) %>% 
  mutate(abun = dnorm(length, mean = 30, sd = 3)) %>% 
  mutate(selected_abun = 
           abun*logistic_selection(abun, l50=25, l95=50)) %>% 
  ggplot(aes(x, y)) +
  geom_line() +
  geom_line(aes(y = y2), col = "red")


```


## Figure 1

```{r}

fig1 <- 
  sim_select_summary %>%
  # filter(m %in% c(0.05, 0.1, 0.2, 0.4), 
  #            k %in% c(0.1, 0.2, 0.4, 0.8), 
  #        cv_a == 0.1) %>% 
  filter(m %in% c(0.2, 0.3, 0.4),
             k %in% c(0.4, 0.2, 0.2),
  cv_a == 0.1) %>%
  mutate(mk = m/k, 
         l95_const = l95/l50) %>% 
  ggplot() +
  aes(x = l50, 
      y = l95_const, 
      fill = cv, col = NULL) +
  geom_tile() +
  scale_fill_continuous_diverging(
    palette = "Blue-Red 3", 
    mid = 0.34) +
  facet_grid(m~sim) + 
  scale_x_continuous(limits = c(NA, 30)) +
  scale_y_continuous(limits = c(NA, 1.5)) + 
  geom_vline(xintercept = c(10, 15, 20))

ggsave(fig1, filename = "fig1.png", 
       height = 10, width = 10)
```

## Figure 2 - varying CV-at-age

```{r}

fig2 <- 
  sim_summary %>%
  filter(cv_a %in% c(0.05, 0.1, 0.2)) %>% 
  mutate(k_05 = m/0.5,
         k_10 = m/1.0,
         k_15 = m/1.5,
         k_20 = m/2.0) %>% 
  ggplot() +
  aes(x = m, 
      y = k, 
      fill = cv, col = NULL) +
  geom_tile() +
     geom_line(aes(x = m, y = k_05), lty = 2) +
  geom_line(aes(x = m, y = k_10), lty = "13") +
  geom_line(aes(x = m, y = k_15)) +
  geom_line(aes(x = m, y = k_20), lty = "31") +
  scale_fill_continuous_diverging(
    palette = "Blue-Red 3", 
    mid = 0.34) +
  facet_grid(cv_a~sim) +
  scale_y_continuous(limits = c(NA, 1.5))

ggsave(fig2, filename = "fig2.png", 
       height = 10, width = 10)

```

## Figure 3 - 

```{r}

fig3 <- 
sim_binned_summary %>% 
  mutate(type = "binned") %>% 
  bind_rows(sim_summary %>% 
 mutate(type = "unbinned"))%>%
  mutate(k_05 = m/0.5,
         k_10 = m/1.0,
         k_15 = m/1.5,
         k_20 = m/2.0) %>% 
  filter(cv_a == 0.1) %>% 
  ggplot() +
  aes(x = m, 
      y = k, 
      fill = cv, col = NULL) +
  geom_tile() +
   geom_line(aes(x = m, y = k_05), lty = 2) +
  geom_line(aes(x = m, y = k_10), lty = "13") +
  geom_line(aes(x = m, y = k_15)) +
  geom_line(aes(x = m, y = k_20), lty = "31") +
  scale_fill_continuous_diverging(
    palette = "Blue-Red 3", 
    mid = 0.34) +
  scale_y_continuous(limits = c(NA, 1.5)) +
  facet_grid(type~sim)

ggsave(fig3, filename = "fig3_V2.png", 
       height = 10, width = 10)

```

